name: Deploy website
run-name: deploying website 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global url.https://${{ secrets.SA_TOKEN }}@github.com/.insteadOf https://github.com/
      - uses: actions/checkout@v4
        with:
          token: '${{ secrets.SA_TOKEN }}'
      - run: git remote set-url origin "https://${{ secrets.SA_TOKEN }}@github.com/adrienligne/adrienligne.github.io.git"
      - run: npm install
      - run: npm run deploy
