name: Deploy website
run-name: deploying website 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install &&
          gh auth login --with-token < <<EOF
          ${{ secrets.SA_TOKEN }}
          EOF&&
          npm run deploy
