name: Deploy website
run-name: deploying website 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: git remote set-url origin https://x-access-token:${{ secrets.SA_TOKEN }}@github.com:AdrienLIGNE/adrienligne.github.io.git
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SA_TOKEN }}
      - run: npm install
      - run: npm run deploy
