name: Deploy website
run-name: deploying website 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.password "${{ secrets.SA_TOKEN }}"
      - run: git config --global user.email "${{ vars.SA_EMAIL }}"
      - run: git config --global user.name "${{ vars.SA_NAME }}"
      - run: npm install
      - run: npm run deploy
