name: Deploy website
run-name: deploying website 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SA_TOKEN }}
      - run: npm install
      - run: npm run deploy
