name: Deploy website
run-name: deploying website 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:
          echo "${{ secrets.SA_TOKEN }}" > token.txt
          gh auth login --with-token < token.txt &&
          npm install &&
          npm run deploy
